### ISSUE TITLE
Add function for finding all possible paths from a given node

### ISSUE THREAD

**Issue by runeksvendsen** [patrickdoc/hash-graph#4]
The `Graphalyze` library has the useful [`pathTree`](https://hackage.haskell.org/package/Graphalyze-0.15.0.0/docs/Data-Graph-Analysis-Algorithms-Common.html#v:pathTree) function, which finds all possible paths from a given node. It would be very useful to have such a function in `Data.HashGraph.Algorithms`.

This is connected to the currency exchange example from #3, where we could imagine having a graph consisting of the following edges:

    [ SomeExchangeRate “EUR” “USD” 1.2
    , SomeExchangeRate “USD” “GBP” 0.6
    , SomeExchangeRate “EUR” “JPY” 136
    , SomeExchangeRate “JPY” “GBP” 0.006
    ]

As we can see there are two possible paths from “EUR” to “GBP”: one through “USD” and one through “JPY” and — depending on the various exchange rates — one path might be more profitable than another.

**Comment by patrickdoc** [comment]
Ok, I have added an example demonstrating how this might work. Forgive my handling of the `Money` values, I've not used it before, so it may be less than optimal.

https://github.com/patrickdoc/hash-graph/blob/dc2f9ba6f1a68e3f687031d1bed487279da6aebd/examples/Currency.hs#L14-L17

I've implemented a rough version of `pathTree`. My only warning is that it will infinitely loop on graphs containing self loops (e.g. an edge from "USD" to "USD"). This will return a list of edges, which should not lose any information from the graph.

**Comment by runeksvendsen** [comment]
Wonderful! Thanks a lot for implementing this, and doing it so fast.

Would you happen to know the time complexity of your
`pathTree` implementation?

**Comment by patrickdoc** [comment]
Hm, so I mostly used the algorithm from Graphalyze, which recursively calls `match`. I believe worst-case you are looking at something like N<sup>2</sup>E.

**Comment by runeksvendsen** [comment]
Great. I won't be using it for huge graphs, so I hope that won't become a problem.

I finally got the time to try out `pathTree` properly. I've extended the "Currency"/exchange rate example to a total of eight edges with four possible paths of length five (along with some pretty printing). See PR #5.
